version: '3.7'

networks:
  permissions_roles-ambiente:
    name: permissions_roles-ambiente
    driver: bridge
volumes:
  permissions_roles_mysql-data:
    name: permissions_roles_mysql-data
    driver: local

services:
  app:
    build:
      context: ./app #onde vai buscar o arquivo para ser buildado
      dockerfile: Dockerfile #nome do arquivo do tipo dockerfile
    container_name: app
    restart: always
    ports: 
      - 8080:80
    stdin_open: true
    tty: true
    volumes: 
      - ./app:/var/www/html
    depends_on:
      - mysql
    networks:
      - permissions_roles-ambiente
      
  mysql:
    image: mysql:5.7
    container_name: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password-root
      MYSQL_DATABASE: app
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports: 
      - 3307:3306
    volumes:
      - permissions_roles_mysql-data:/var/lib/mysql
    networks:
      - permissions_roles-ambiente